import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SiteHeader from "./components/SiteHeader";
import SiteFooter from "./components/SiteFooter";
import { UserProvider } from "./contexts/UserContext"; // Import the UserProvider
import { AuthProvider } from "./contexts/AuthContext"; // Import the AuthProvider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Context wraps here */}
        {/* 6 - Add AuthProvider */}
        <AuthProvider>
          <UserProvider>
            <SiteHeader />
            {children}
            <SiteFooter />
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
